export interface AuthUser {
  id: string,
  identity_id: string,
  user_code: string,
  first_name: string,
  last_name: string,
  email: string,
  email_verified_at: Date | null,
  address: string | null,
  phone_number: string | null,
  avatar: string | null,
  background_profile: string | null,
  from_ward_id: number | null,
  from_district_id: number | null,
  from_city_id: number | null,
  current_ward_id: number | null,
  current_district_id: number | null,
  current_city_id: number | null,
  type_account: number,
  job_id: number | null,
  organization_id: number,
  unit_room_id: number | null,
  position_id: number,
  relationship_status: null,
  gender: number,
  day_of_birth: number,
  month_of_birth: number,
  year_of_birth: number,
  about_me: string | null,
  latest_login: Date | null,
  latest_ip_login: string,
  last_activity_at: null,
  status: number,
  status_active: number,
  created_at: Date,
  updated_at: Date,
  deleted_at: Date | null
}